---
# tasks file for visibike.jsondumpster

# - name: Add EPEL repository
#   yum: name=epel-release state=present

- name: Shut down service for maintenance
  service: name=jsondumpster state=stopped
  ignore_errors: yes

- name: Install aptitude needed by system upgrade
  apt: name=aptitude state=present

- name: Upgrade system
  apt: upgrade=safe

- name: Install dependencies
  apt: name={{ item }} state=latest
  with_items:
    - python3-pip
    - python3-dev
    - python3-venv
    - python-psycopg2 # Needed for postgresql modules
    - libpq-dev
    - postgresql
    - postgresql-contrib
    - nginx

- name: Enable and start postgresql
  service: name=postgresql enabled=yes state=started

- name: Create jsondumpster database
  postgresql_db: name="{{ jsondumpster_db }}"
  become_user: postgres

- name: Create jsondumpster user
  user: name="{{ jsondumpster_user }}"

- name: Create jsondumpster postgres user
  postgresql_user:
    db="{{ jsondumpster_db }}"
    name="{{ jsondumpster_user }}"
    password="{{ jsondumpster_psql_password }}"
  become_user: postgres

- name: Delete app directory
  file:
    path="{{ jsondumpster_path }}"
    state=absent

- name: Create service root folder
  file:
    path="{{ jsondumpster_root }}"
    state=directory
    mode=755
    owner="{{ jsondumpster_user }}"
    group="{{ jsondumpster_user }}"

# TODO: there is certainly a better way to deploy the code than rsyncing it
# over.
- name: Copy over app
  synchronize:
    src="../../../../"
    dest="{{ jsondumpster_path }}"

- name: Disable debug mode
  lineinfile:
    dest="{{ jsondumpster_settings }}"
    regexp="^DEBUG[ =]"
    line="DEBUG = False"

- name: Change secret key
  lineinfile:
    dest="{{ jsondumpster_settings }}"
    regexp="^SECRET_KEY[ =]"
    line='SECRET_KEY = "{{ jsondumpster_secret_key }}"'

- name: Add allowed hosts
  lineinfile:
    dest="{{ jsondumpster_settings }}"
    regexp="^ALLOWED_HOSTS[ =]"
    line='ALLOWED_HOSTS = ["{{ jsondumpster_hostname }}"]'

- name: Set permissions
  file:
    path="{{ jsondumpster_path }}"
    state=directory
    recurse=yes
    mode=755
    owner="{{ jsondumpster_user }}"
    group="{{ jsondumpster_www_group }}"

- name: Initialize virtualenv
  pip:
    requirements="{{ jsondumpster_path }}/requirements.txt"
    virtualenv="{{ jsondumpster_venv }}"
    virtualenv_command=pyvenv
  become_user: "{{ jsondumpster_user }}"

- name: Run migrations
  command: "{{ jsondumpster_venv }}/bin/python {{ jsondumpster_manage_py }} migrate"
  become_user: "{{ jsondumpster_user }}"

- name: Collect static files
  command: "{{ jsondumpster_venv }}/bin/python {{ jsondumpster_manage_py }} collectstatic --noinput"
  become_user: "{{ jsondumpster_user }}"

- name: Deploy systemd service
  template: src=jsondumpster.service dest=/etc/systemd/system/jsondumpster.service

# TODO: systemctl module in Ansible 2.2
- name: Reload daemon files
  command: systemctl daemon-reload

- name: Enable and restart systemd service
  service: name=jsondumpster enabled=yes state=restarted

- name: Set letsencrypt fact to false to deploy http-only version of nginx config
  set_fact:
    jsondumpster_letsencrypt: False

- name: Deploy nginx config
  template: src=jsondumpster.nginx dest="{{ jsondumpster_nginx_available }}"

- name: Enable nginx config
  file:
    src="{{ jsondumpster_nginx_available }}"
    dest="{{ jsondumpster_nginx_enabled }}"
    state=link

- name: Delete default nginx config
  file:
    path=/etc/nginx/sites-enabled/default
    state=absent

- name: Enable and restart nginx service
  service: name=nginx enabled=yes state=reloaded

# letsencrypt setup starts here

- name: Install letsencrypt
  apt: name=letsencrypt state=latest

- name: Create letsencrypt webroot folder
  file:
    name="{{ jsondumpster_letsencrypt_webroot_path }}"
    state=directory
    group="{{ jsondumpster_www_group }}"
    mode=755

- name: Create letsencrypt config folder
  file:
    name="{{ jsondumpster_letsencrypt_config_directory }}"
    state=directory

- name: Deploy letsencrypt config
  template:
    src=jsondumpster.letsencrypt
    dest="{{ jsondumpster_letsencrypt_config }}"

- name: Check if certificate exists
  stat:  path="{{ jsondumpster_cert_path }}"
  register: jsondumpster_cert_found

- name: Get the certificate
  command: "letsencrypt certonly --config {{ jsondumpster_letsencrypt_config }} --agree-eula --agree-tos"
  args:
    creates="{{ jsondumpster_cert_path }}"
  when: not jsondumpster_cert_found.stat.isdir

- name: Set letsencrypt fact to true to deploy https version of nginx config
  set_fact:
    jsondumpster_letsencrypt: True

- name: Deploy nginx config
  template: src=jsondumpster.nginx dest="{{ jsondumpster_nginx_available }}"

- name: Restart nginx service
  service: name=nginx state=reloaded

- name: Deploy certificate renewal service
  template:
    src=jsondumpster.letsencrypt.service
    dest=/etc/systemd/system/letsencrypt.service

- name: Deploy certificate renewal timer
  template:
    src=jsondumpster.letsencrypt.timer
    dest="/etc/systemd/system/{{ jsondumpster_letsencrypt_timer }}"

- name: Enable certificate renewal timer
  service:
    name="{{ jsondumpster_letsencrypt_timer }}"
    enabled=yes

# Backup functionality
- name: Install autopostgresqlbackup
  apt: name=autopostgresqlbackup state=present

- name: Deploy backup service
  template:
    src=autopostgresqlbackup.service
    dest=/etc/systemd/system/autopostgresqlbackup.service

- name: Deploy backup timer
  template:
    src=autopostgresqlbackup.timer
    dest="/etc/systemd/system/{{ jsondumpster_autopostgresqlbackup_timer }}"

# TODO: systemctl module in Ansible 2.2
- name: Reload daemon files
  command: systemctl daemon-reload

- name: Enable backup timer
  service:
    name="{{ jsondumpster_autopostgresqlbackup_timer }}"
    enabled=yes
