# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 07:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
